### ISSUE TITLE
Publishing to Maven Central

### ISSUE THREAD

**Issue by ctapobep** [BlueObelisk/chemdraw-converter#8]
Are there any plans to publish the lib to the Maven Central? I can't find it at the moment: https://mvnrepository.com/artifact/org.xml-cml

I was looking for a tool to read CDX(ML) in Java. CDK doesn't seem to support it. But seems like you've implemented a conversion to CML, and then we can use CDK to parse CML further.

**Comment by egonw** [comment]
I can have a look at it... I cannot promise when I know more. For a first glance, we first need to:

- [x] set up CI
- [x] set up Jumbo6 as Maven Central, or perhaps cmlxom-tools
- [x] compile against the latest libraries
- [x] change the Maven group to be in line with the CMLXOM libs

**Comment by egonw** [comment]
I intend to copy https://github.com/BlueObelisk/jumbo-testutil/blob/master/src/main/java/org/xmlcml/cml/testutil/JumboTestUtils.java for now

**Comment by ctapobep** [comment]
Question.. Does it make sense to maybe just include this as part of the CDK? It already has the CI part. Or it's going to take more work because you'd need to convert it into CDK objects?

**Comment by egonw** [comment]
> Does it make sense to maybe just include this as part of the CDK?

I am not sure at this moment, but I would tentatively say a port of this code to the CDK is indeed interesting.

**Comment by egonw** [comment]
Looks like we're first going to have to get https://github.com/BlueObelisk/jumbo6 mavenized :(

And this depends at least on https://github.com/BlueObelisk/html to be on Maven Central too...

**Comment by ctapobep** [comment]
Hm.. It's weird that a project that converts between 2 chemical formats depends on something HTML-related. It feels more and more that this CDXML-parsing logic should reside in CDK after all. Maybe I'll have time to help with this next year.. I doubt it, but I'll keep hoping :)

**Comment by egonw** [comment]
> Hm.. It's weird that a project that converts between 2 chemical formats depends on something HTML-related.

It doesn't. But it depends on classes in Jumbo6 and that has (likely independent code) that depends on that.

I haven't given up yet :)

**Comment by ctapobep** [comment]
Ah, I guess it's because CML is ["HTML with some chemistry added"](https://www.ch.ic.ac.uk/rzepa/cml/#:~:text=CML%20allows%20definition%20of%3A,formats%20chosen%20in%20chemical%20MIME). I haven't worked with this format before, didn't realize that.

**Comment by egonw** [comment]
>Ah, I guess it's because CML is "HTML with some chemistry added"

Not literally! (Sorry, did not intend to edit your comment! corrected now)

**Comment by egonw** [comment]
@ctapobep, I got it compiling now.

- [x] explore the test failure

**Comment by egonw** [comment]
Okay, I got something compiling and testing. Next up is https://github.com/BlueObelisk/chemdraw-converter/issues/7

**Comment by egonw** [comment]
Okay, the `0.5-SNAPSHOT` is now available as snapshot release. Use something like this in your `pom.xml` (I think):

```xml
<distributionManagement>
  <snapshotRepository>
    <id>ossrh</id>
    <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
  </snapshotRepository>
</distributionManagement>
```

And, of course, the dependency:

```xml
<dependencies>
  <dependency>
    <groupId>org.blueobelisk</groupId>
    <artifactId>chemdraw-converter</artifactId>
    <version>0.5-SNAPSHOT</version>
  </dependency>
</dependencies>
```

**Comment by egonw** [comment]
hi @ctapobep, have you been able to give it a spin? Got feedback?

I have pushed 0.5 to Maven Central, so you can now use it without the snapshot repository, and just use:

```xml
<dependencies>
  <dependency>
    <groupId>org.blueobelisk</groupId>
    <artifactId>chemdraw-converter</artifactId>
    <version>0.5</version>
  </dependency>
</dependencies>
```

**Comment by egonw** [comment]
Okay, if things can up, please file them as new issues.

**Comment by ctapobep** [comment]
I ran into additional obstacles with my files - they appeared to have dative bonds, which aren't supported by CDK so far. So I parked this activity for now and haven't really tested this library, sorry.

But overall I have some concerns regarding the design - it fetches a lot of dependencies like log4j (which should probably be `slf4j-api`, with `log4j` possibly as `provided` dependency?), joda-time, etc. 

Also, when things get serious I'd hope to try to incorporate the logic right into cdk as this would allow not to do the conversion of the formats twice.

**Comment by egonw** [comment]
> they appeared to have dative bonds, which aren't supported by CDK so far.

cc @johnmay

**Comment by johnmay** [comment]
Well we sort of support them... I've done a lot on ChemDraw passing at NextMove - I could add one but the tricky part is ChemDraw is more like SVG than a chemical file format. There is often lots of cleanup needed to get anything useful out.

Doing it for CDK I would ideally like to capture parts like the side of bond a double bond is on. You can do this for example:

![image](https://github.com/BlueObelisk/chemdraw-converter/assets/983232/30981805-88f9-4bcb-91e5-90c881aa4c80)
